[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.openssl",
  "php82Extensions.json",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.dom",
  "php82Extensions.zip"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port ${PORT:-3000}"

